services:
  go-grpc:
    build:
      context: ./src/go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
    command: "go-grpc"
