[project]
name = "python-quickstart"
version = "0.1.0"
description = "Python quickstart project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "exceptiongroup>=1.2.2",
    "fastmcp>=2.2.5",
    "mcp>=1.6.0",
    "openai>=1.76.0",
]
