[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
    "openai>=1.74.0",
    "ruff>=0.11.5",
    "urllib3>=2.4.0",
]
