openapi: '3.0.0'
info:
  title: Swagger Hub - OpenAPI 3.1
  description: |-
    This is a Hub Server based on the OpenAPI 3.1 specification.
  version: '1.0.1'
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Workspaces
    description: Workspaces management
  - name: Projects
    description: Projects management
  - name: Environments
    description: Environments management
  - name: Applications
    description: Applications management
paths:
  /projects:
    #    get:
    #      $ref: 'resources/hub/projects_list.yml'
    post:
      $ref: 'resources/hub/projects_create.yml'
#  /v1/projects/{project_id}:
#    get:
#      $ref: 'resources/hub/projects_get.yml'
#
#    put:
#      $ref: 'resources/hub/projects_update.yml'
#
#    patch:
#      $ref: 'resources/hub/projects_patch.yml'
#
#    delete:
#      $ref: 'resources/hub/projects_delete.yml'