openapi: 3.1.0
info:
  title: Quickstart Definition - OpenAPI 3.1
  version: '1.0.1'
servers:
  - url: 'https://localhost:8080/api'
  - url: 'https://api.quickstart.com/api'
tags:
  - name: Actions
    description: Action management
  - name: Permissions
    description: Permissions management
  - name: Roles
    description: Roles management
paths:
  /v1/actions:
    post:
      $ref: 'resources/role/actions_create.yml'
    get:
      $ref: 'resources/role/actions_list.yml'
  /v1/actions/{action_id}:
    get:
      $ref: 'resources/role/actions_get.yml'
    put:
      $ref: 'resources/role/actions_update.yml'
    patch:
      $ref: 'resources/role/actions_patch.yml'
    delete:
      $ref: 'resources/role/actions_delete.yml'
  /v1/permissions:
    post:
      $ref: 'resources/role/permissions_create.yml'
    get:
      $ref: 'resources/role/permissions_list.yml'
  /v1/permissions/{permission_id}:
    get:
      $ref: 'resources/role/permissions_get.yml'
    put:
      $ref: 'resources/role/permissions_update.yml'
    patch:
      $ref: 'resources/role/permissions_patch.yml'
    delete:
      $ref: 'resources/role/permissions_delete.yml'
  /v1/roles:
    post:
      $ref: 'resources/role/roles_create.yml'
    get:
      $ref: 'resources/role/roles_list.yml'
  /v1/roles/{role_id}:
    get:
      $ref: 'resources/role/roles_get.yml'
    put:
      $ref: 'resources/role/roles_update.yml'
    patch:
      $ref: 'resources/role/roles_patch.yml'
    delete:
      $ref: 'resources/role/roles_delete.yml'
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: jwt
    basic_auth:
      type: http
      scheme: basic
    apikey_auth:
      type: apiKey
      in: header
      name: X-API-Key
    oauth_user:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:8080/api/v1/oauth/authorize
          tokenUrl: http://localhost:8080/api/v1/oauth/token
          scopes:
            read: Read access
            write: Write access
    oauth_app:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: http://localhost:8080/api/v1/oauth/token
          scopes:
            board:read: Read the board
security:
  - bearer_auth: [ ]
  - apikey_auth: [ ]