per_page:
  in: query
  name: per_page
  required: false
  description: Number of items returned per page
  schema:
    type: integer
    minimum: 1
    default: 20
    maximum: 200
  example: 2

page:
  in: query
  name: page
  required: false
  description: Which 'page' of paginated results to return.
  schema:
    type: integer
    minimum: 1
    default: 1
  example: 1

sort:
  in: query
  name: sort
  required: false
  description: Sorting criteria for the list, using a "+" or "-" prefix to specify ascending or descending order.
  schema:
    type: array
    items:
      type: string
      pattern: '^(\+|-)[a-zA-Z0-9_]+$'
  example: [ '+name', '-age' , "address" ]