project_id:
  name: project_id
  description: A unique identifier for a project.
  in: path
  required: true
  schema:
    type: string
    format: uuid
    minimum: 1
  style: simple

project_search_filter:
  name: searchFilter
  description: search filter condition for list projects
  in: query
  required: true
  schema:
    $ref: './models/project.yml#/project_base'
  style: form